notification_times = [
  "12:00"
]

priority_companies = [
  "Zalando",
  "Delivery Hero",
  "HelloFresh",
  "N26",
  "AUTO1 Group",
  "Trade Republic",
  "GetYourGuide",
  "Raisin",
  "Omio",
  "sennder",
  "Contentful"
]

jobdatafeeds_job_titles = [
  "business",
  "operations",
  "strategy"
]

jsearch_job_titles = [
  "business analyst",
  "operations analyst",
  "strategy analyst",
  "project manager"
]

excluded_job_title_markers = [
  "HR",
  "Account",
  "Senior",
  "Technical",
  "Representative",
  "People",
  "FinOps",
  "Engineering",
  "Techno",
  "Engineer",
  "Security",
  "Vice President",
  "Head",
  "Lead",
  "Director",
  "VP",
  "Principal",
  "Chief"
]
